export const Hairdos=[
    {
        name:'ladies-cut-and-finish',
        minDuration:45,
        maxDuration:60,
        type:'styling',
        priceRange:'',
        description:''
    },{
        name:'ladies-finish',
        minDuration:45,
        maxDuration:60,
        type:'styling',
        description:''
    },{
        name:'half-head-highlights',
        minDuration:45,
        maxDuration:60,
        type:'colours',
        description:''
    },{
        name:'three-quarter-head-highlights',
        minDuration:45,
        maxDuration:60,
        type:'colours',
        description:''
    },{
        name:'ladies-cut-and-finish',
        minDuration:45,
        maxDuration:60,
        type:'styling',
        priceRange:'',
        description:''
    },{
        name:'ladies-finish',
        minDuration:45,
        maxDuration:60,
        type:'styling',
        description:''
    },{
        name:'half-head-highlights',
        minDuration:45,
        maxDuration:60,
        type:'colours',
        description:''
    },{
        name:'three-quarter-head-highlights',
        minDuration:45,
        maxDuration:60,
        type:'colours',
        description:''
    }
];